export interface Program {
  _id?: string;
  id: string;
  name: string;
  shortName?: string;
  date: string;
  time?: string;
  price?: number;
  currency?: string;
  city?: string;
  venue?: string;
  venueAddress?: string;
  mapUrl?: string;
  description?: string;
  headline?: string;
  subheadline?: string;
  highlights?: string[] | string;
  instructions?: string[] | string;
  heroImage?: string;
  posterImage?: string;
  contactPhone?: string;
  contactWhatsapp?: string;
  contactEmail?: string;
  speakerName?: string;
  speakerTitle?: string;
  speakerImage?: string;
  speakerBio?: string;
  ctaLabel?: string;
  passTitle?: string;
  passInstructions?: string;
  seoTitle?: string;
  seoDescription?: string;
  status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled' | 'date_tba' | 'few_seats' | 'housefull' | 'registration_closed' | 'archived' | string;
  slug?: string;
  featured?: boolean;
  registrationMode?: 'internal' | 'external';
  externalRegistrationUrl?: string;
  capacity: number;
  isDateFinal?: boolean;
  cardTemplate?: string | null;
  heartX?: number;
  heartY?: number;
  heartWidth?: number;
  heartHeight?: number;
  photoZoom?: number;
  photoOffsetY?: number;
  photoLink?: string;
  isInquiryClosed?: boolean;
  bookingsCount: number;
  activeBookings?: number;
  availableSeats?: number;
  isSoldOut?: boolean;
  inquiryCount?: number;
  pendingCount?: number;
  approvedCount?: number;
  rejectedCount?: number;
  cplApproved?: number;
  cplPending?: number;
  cplInquiry?: number;
  ipApproved?: number;
  ipPending?: number;
  ipInquiry?: number;
  sequenceNumber?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface GlobalSettings {
  _id?: string;
  key: string;
  upiId: string;
  upiIds: string[];
  activeUpiIndex: number;
  upiBookingsCount: number;
  upiLimit: number;
  payeeName: string;
  amount: string;
  brandName?: string;
  supportPhone?: string;
  supportWhatsapp?: string;
  supportEmail?: string;
  websiteEmail?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  youtubeUrl?: string;
  linktreeUrl?: string;
  defaultCity?: string;
  defaultCountry?: string;
  defaultCurrency?: string;
  defaultPrice?: number;
  defaultSpeakerName?: string;
  defaultSpeakerTitle?: string;
  defaultRegistrationInstructions?: string;
  defaultPassInstructions?: string;
  defaultFooterCopy?: string;
}
