export interface Program {
  _id?: string;
  id: string;
  name: string;
  date: string;
  time?: string;
  price?: number;
  city?: string;
  venue?: string;
  mapUrl?: string;
  status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled' | string;
  slug?: string;
  registrationMode?: 'internal' | 'external';
  externalRegistrationUrl?: string;
  capacity: number;
  isDateFinal?: boolean;
  cardTemplate?: string | null;
  heartX?: number;
  heartY?: number;
  heartWidth?: number;
  heartHeight?: number;
  photoZoom?: number;
  photoOffsetY?: number;
  photoLink?: string;
  isInquiryClosed?: boolean;
  bookingsCount: number;
  inquiryCount?: number;
  pendingCount?: number;
  approvedCount?: number;
  rejectedCount?: number;
  cplApproved?: number;
  cplPending?: number;
  cplInquiry?: number;
  ipApproved?: number;
  ipPending?: number;
  ipInquiry?: number;
  sequenceNumber?: number;
  createdAt?: string;
  updatedAt?: string;
}
